# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#flutter_application_path = '../MultEngineDemo/engine_web'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'EnginePJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  #install_all_flutter_pods(flutter_application_path)

  # Pods for EnginePJ

  pod 'engine_web', :path => '../engine_web'

  target 'EnginePJTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnginePJUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
             end
        end
 end
end
